Repository wecode-bootcamp-korea/40-backend-westagram-3, pull requests merged in 2022-11, with the labels that each got.

#1 [40기 - 원승현] Assignment 1: Express API - 초기 환경 세팅
  WonSeungHyun/.env.sample
  WonSeungHyun/.gitignore
  WonSeungHyun/app.js
  WonSeungHyun/package-lock.json
  WonSeungHyun/package.json
Labels: 멘토 리뷰 요청

#7 [40기 - 원승현] Assignment 2: Express API - 유저 회원가입 하기
  WonSeungHyun/.gitignore
  WonSeungHyun/app.js
  WonSeungHyun/db/migrations/20221124051443_create_users_table.sql
  WonSeungHyun/db/migrations/20221124051509_create_posts_table.sql
  WonSeungHyun/package-lock.json
  WonSeungHyun/package.json
Labels: 멘토 리뷰 요청

#12 [40기-전형진]Assignment1:Express API - 초기 환경 세팅
  .gitignore
  hyunjinjeon/.env.sample
  hyunjinjeon/.gitignore
  hyunjinjeon/app.js
  hyunjinjeon/db/migrations/20221124075625_create_signup.sql
  hyunjinjeon/db/migrations/20221124083118_create_posts_table.sql
  hyunjinjeon/db/migrations/20221124113331_create_postcheck_table.sql
  hyunjinjeon/db/migrations/20221127063157_create_signup_table.sql
  hyunjinjeon/db/migrations/20221127063800_create_post_table.sql
  hyunjinjeon/db/migrations/20221127064131_create_signup_table.sql
  hyunjinjeon/db/migrations/20221127064632_create_post_table.sql
  hyunjinjeon/package-lock.json
  hyunjinjeon/package.json
Labels: Assignment 1 - 리뷰 선반영 요청, 멘토 리뷰 요청

#10 [40기-전형진]Assignment2:Express API - 유저 회원 가입 하기
  .gitignore
  hyunjinjeon/.gitignore
  hyunjinjeon/app.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청
